### ISSUE TITLE
Error : TypeError [ERR_INVALID_ARG_TYPE]

### ISSUE THREAD

**Issue by plengeh69** [MhankBarBar/termux-wabot#34]
Error : TypeError [ERR_INVALID_ARG_TYPE]: The "url" argument must be of type string. Received undefined
(node:11655) UnhandledPromiseRejectionWarning: TypeError [ERR_INVALID_ARG_TYPE]: The "data" argument must be of type string or an instance of Buffer, TypedArray, or DataView. Received undefined
    at Cipheriv.update (internal/crypto/cipher.js:157:11)
    at Object.aesEncrypWithIV (/storage/emulated/0/Download/termux-wabot/node_modules/@adiwajshing/baileys/lib/WAConnection/Utils.js:111:31)
    at WAConnection.prepareMessageMedia (/storage/emulated/0/Download/termux-wabot/node_modules/@adiwajshing/baileys/lib/WAConnection/6.MessagesSend.js:120:29)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
    at async WAConnection.prepareMessageContent (/storage/emulated/0/Download/termux-wabot/node_modules/@adiwajshing/baileys/lib/WAConnection/6.MessagesSend.js:81:21)
    at async WAConnection.prepareMessage (/storage/emulated/0/Download/termux-wabot/node_modules/@adiwajshing/baileys/lib/WAConnection/6.MessagesSend.js:30:25)
    at async WAConnection.sendMessage (/storage/emulated/0/Download/termux-wabot/node_modules/@adiwajshing/baileys/lib/WAConnection/6.MessagesSend.js:24:27)
(node:11655) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 5)

**Comment by MhankBarBar** [comment]
sorry I am not a shaman
